"use client";
/* eslint-disable @next/next/no-img-element */

import { CheckCircle2, Download, KeyRound, RefreshCw, ShieldCheck, WandSparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { CopyButton } from "@/components/copy-button";
import { canvasToBlob, downloadBlob, loadImage } from "@/lib/browser-files";
import { InfoBlock } from "./image-tools";

function OutputCard({ title, value, language = "text" }: { title: string; value: string; language?: string }) {
  return <div className="code-card output-card"><div className="code-card-head"><span>{title}<small>{language}</small></span><CopyButton text={value} /></div><pre>{value || "입력하면 결과가 여기에 표시됩니다."}</pre></div>;
}

export function MetadataTool() {
  const [mode, setMode] = useState("Next.js"); const [name, setName] = useState("My Service"); const [title, setTitle] = useState("My Service | 더 나은 작업을 위한 도구"); const [description, setDescription] = useState("서비스를 한 문장으로 명확하게 설명하세요."); const [url, setUrl] = useState("https://example.com"); const [og, setOg] = useState("https://example.com/og.png"); const [twitter, setTwitter] = useState("https://example.com/og.png"); const [theme, setTheme] = useState("#ffffff");
  const output = useMemo(() => mode === "Next.js" ? `import type { Metadata } from "next";\n\nexport const metadata: Metadata = {\n  metadataBase: new URL("${url}"),\n  title: "${escapeQuote(title)}",\n  description: "${escapeQuote(description)}",\n  alternates: { canonical: "/" },\n  openGraph: {\n    title: "${escapeQuote(title)}",\n    description: "${escapeQuote(description)}",\n    url: "${url}",\n    siteName: "${escapeQuote(name)}",\n    images: [{ url: "${og}", width: 1200, height: 630 }],\n    type: "website",\n  },\n  twitter: {\n    card: "summary_large_image",\n    title: "${escapeQuote(title)}",\n    description: "${escapeQuote(description)}",\n    images: ["${twitter}"],\n  },\n  themeColor: "${theme}",\n};` : `<title>${htmlEscape(title)}</title>\n<meta name="description" content="${htmlEscape(description)}">\n<link rel="canonical" href="${url}">\n<meta name="theme-color" content="${theme}">\n\n<meta property="og:type" content="website">\n<meta property="og:site_name" content="${htmlEscape(name)}">\n<meta property="og:title" content="${htmlEscape(title)}">\n<meta property="og:description" content="${htmlEscape(description)}">\n<meta property="og:url" content="${url}">\n<meta property="og:image" content="${og}">\n\n<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:title" content="${htmlEscape(title)}">\n<meta name="twitter:description" content="${htmlEscape(description)}">\n<meta name="twitter:image" content="${twitter}">`, [mode, name, title, description, url, og, twitter, theme]);
  return <div className="workbench-stack"><section className="workbench two-col"><div className="panel"><div className="panel-head"><span>01</span><div><h2>사이트 정보</h2><p>검색과 공유 화면에 사용할 내용을 입력하세요.</p></div></div><div className="form-stack"><label>사이트 이름<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Description<textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Production URL<input type="url" value={url} onChange={(e) => setUrl(e.target.value)} /></label><label>OG Image URL<input type="url" value={og} onChange={(e) => setOg(e.target.value)} /></label><label>Twitter/X Image<input type="url" value={twitter} onChange={(e) => setTwitter(e.target.value)} /></label><label>Theme Color<span className="input-with-color"><input type="color" value={theme} onChange={(e) => setTheme(e.target.value)} /><input value={theme} onChange={(e) => setTheme(e.target.value)} /></span></label></div></div><div className="panel result-panel"><div className="panel-head"><span>02</span><div><h2>생성 코드</h2><p>프로젝트 방식에 맞는 코드를 복사하세요.</p></div></div><div className="template-tabs">{["Next.js", "HTML"].map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{item}</button>)}</div><OutputCard title="Metadata" value={output} language={mode === "HTML" ? "html" : "typescript"} /></div></section><InfoBlock title="메타데이터 작성 팁" items={[{ h: "제목과 설명은 페이지마다", p: "검색 결과에서 중복되지 않도록 각 페이지의 실제 목적과 내용을 구체적으로 적으세요." }, { h: "URL은 운영 주소로", p: "localhost가 아닌 실제 배포 주소를 사용하고 canonical과 OG URL의 도메인을 일치시키세요." }]} /></div>;
}

const envPresets: Record<string, string[]> = { "Next.js": ["NEXT_PUBLIC_APP_URL", "NEXT_PUBLIC_API_URL"], Supabase: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"], Vercel: ["VERCEL_URL", "VERCEL_ENV"], Auth: ["AUTH_SECRET", "AUTH_URL"], Database: ["DATABASE_URL", "DIRECT_URL"] };

export function EnvTool() {
  const [selected, setSelected] = useState<string[]>(["Next.js"]); const [raw, setRaw] = useState("# Database\nDATABASE_URL=postgres://user:password@host/db\n\nAPI_KEY=super-secret-value");
  const template = useMemo(() => selected.flatMap((key) => [`# ${key}`, ...envPresets[key].map((name) => `${name}=`), ""]).join("\n").trim(), [selected]);
  const example = useMemo(() => raw.split(/\r?\n/).map((line) => { const trimmed = line.trim(); if (!trimmed || trimmed.startsWith("#") || !line.includes("=")) return line; return `${line.slice(0, line.indexOf("="))}=`; }).join("\n"), [raw]);
  return <div className="workbench-stack"><div className="privacy-banner"><ShieldCheck size={20} /><div><strong>입력한 ENV 값은 브라우저에서만 처리됩니다.</strong><span>서버 전송과 저장을 하지 않으며, 페이지를 닫으면 사라집니다.</span></div></div><section className="workbench two-col"><div className="panel"><div className="panel-head"><span>01</span><div><h2>ENV Template Generator</h2><p>필요한 환경을 골라 빈 템플릿을 만드세요.</p></div></div><div className="preset-checks">{Object.keys(envPresets).map((key) => <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={() => setSelected((now) => now.includes(key) ? now.filter((x) => x !== key) : [...now, key])} /><span>{key}</span><small>{envPresets[key].length}개 변수</small></label>)}</div><OutputCard title=".env template" value={template} language="env" /></div><div className="panel"><div className="panel-head"><span>02</span><div><h2>.env → .env.example</h2><p>값은 지우고 변수명과 주석만 남겨요.</p></div></div><label className="field-label">.env 내용<textarea className="code-input tall" value={raw} spellCheck={false} onChange={(e) => setRaw(e.target.value)} /></label><OutputCard title=".env.example" value={example} language="env" /></div></section></div>;
}

function secureSecret(length: number, urlSafe: boolean, preset: string) { const alphabets: Record<string, string> = { "Random API Key": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "JWT Secret": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_", "Auth Secret": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_", "CRON_SECRET": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "Webhook Secret": "abcdef0123456789" }; let chars = alphabets[preset] ?? alphabets["Random API Key"]; if (!urlSafe) chars += "!@#$%^&*()_+-=[]{}"; const out: string[] = []; const max = 256 - (256 % chars.length); while (out.length < length) { const values = new Uint8Array(Math.max(32, length - out.length)); crypto.getRandomValues(values); for (const value of values) if (value < max && out.length < length) out.push(chars[value % chars.length]); } return out.join(""); }

export function SecretTool() {
  const [preset, setPreset] = useState("Auth Secret"); const [length, setLength] = useState(64); const [urlSafe, setUrlSafe] = useState(true); const [secret, setSecret] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => setSecret(secureSecret(64, true, "Auth Secret")), 0); return () => window.clearTimeout(timer); }, []);
  function update(nextPreset: string, nextLength: number, nextUrlSafe: boolean) { setSecret(secureSecret(nextLength, nextUrlSafe, nextPreset)); }
  return <div className="workbench-stack"><div className="privacy-banner"><ShieldCheck size={20} /><div><strong>Secret은 이 브라우저에서만 생성됩니다.</strong><span>Web Crypto API를 사용하며 서버·DB·localStorage에 저장하지 않습니다.</span></div></div><section className="workbench secret-layout"><div className="panel"><div className="panel-head"><span>01</span><div><h2>생성 옵션</h2><p>용도와 길이를 고르세요.</p></div></div><div className="form-stack"><label>용도<select value={preset} onChange={(e) => { setPreset(e.target.value); update(e.target.value, length, urlSafe); }}>{["Auth Secret", "JWT Secret", "CRON_SECRET", "Webhook Secret", "Random API Key"].map((x) => <option key={x}>{x}</option>)}</select></label><fieldset><legend>길이</legend><div className="choice-pills">{[32, 48, 64, 128].map((value) => <button key={value} className={length === value ? "active" : ""} onClick={() => { setLength(value); update(preset, value, urlSafe); }}>{value}</button>)}</div></fieldset><label className="check-row"><input type="checkbox" checked={urlSafe} onChange={(e) => { setUrlSafe(e.target.checked); update(preset, length, e.target.checked); }} /> URL Safe 문자만 사용</label></div></div><div className="panel secret-result"><span className="secret-symbol"><KeyRound size={27} /></span><span className="eyebrow">GENERATED SECRET</span><div className="secret-value">{secret}</div><div className="secret-actions"><CopyButton text={secret} label="Secret 복사" /><button className="secondary-button" onClick={() => setSecret(secureSecret(length, urlSafe, preset))}><RefreshCw size={16} /> 새로 생성</button></div><p><CheckCircle2 size={15} /> {length}자 · 암호학적으로 안전한 난수</p></div></section></div>;
}

type Shape = null | boolean | number | string | Shape[] | { [key: string]: Shape };
function pascal(value: string) { const clean = value.replace(/[^a-zA-Z0-9_$]+(.)?/g, (_, c) => c ? c.toUpperCase() : ""); const result = clean.charAt(0).toUpperCase() + clean.slice(1); return /^[A-Za-z_$]/.test(result) ? result : `Type${result}`; }
function primitive(value: Shape): string { if (value === null) return "null"; if (Array.isArray(value)) { if (!value.length) return "unknown[]"; const types = [...new Set(value.map(primitive))]; return `(${types.join(" | ")})[]`; } if (typeof value === "object") return "object"; return typeof value; }
function inferInterfaces(value: Shape, root: string, mode: string) { const blocks: string[] = []; const seen = new Set<string>(); function walk(current: Shape, name: string): string { if (Array.isArray(current)) { if (!current.length) return "unknown[]"; const types = [...new Set(current.map((item) => typeof item === "object" && item !== null && !Array.isArray(item) ? walk(item, `${name}Item`) : primitive(item)))]; return `(${types.join(" | ")})[]`; } if (current && typeof current === "object") { const typeName = pascal(name); if (!seen.has(typeName)) { seen.add(typeName); const lines = Object.entries(current).map(([key, item]) => `  ${/^[$A-Z_][0-9A-Z_$]*$/i.test(key) ? key : JSON.stringify(key)}: ${walk(item, pascal(key))};`); blocks.push(`${mode === "interface" ? `interface ${typeName}` : `type ${typeName} =`} {\n${lines.join("\n")}\n}${mode === "type" ? ";" : ""}`); } return typeName; } return primitive(current); } const rootType = walk(value, root); if (!value || typeof value !== "object" || Array.isArray(value)) blocks.push(`${mode === "interface" ? "type" : "type"} ${pascal(root)} = ${rootType};`); return blocks.reverse().join("\n\n"); }
function jsonError(text: string, error: unknown) { const message = error instanceof Error ? error.message : "올바른 JSON이 아닙니다."; const found = message.match(/position\s+(\d+)/i); if (!found) return message; const pos = Number(found[1]); const before = text.slice(0, pos); const line = before.split("\n").length; const col = pos - before.lastIndexOf("\n"); return `${line}번째 줄 ${col}번째 문자 근처를 확인해 주세요.`; }

export function JsonTypeTool() {
  const [input, setInput] = useState('{\n  "id": 1,\n  "name": "John",\n  "active": true,\n  "profile": {\n    "email": "john@example.com"\n  }\n}'); const [root, setRoot] = useState("Root"); const [mode, setMode] = useState("interface");
  const parsed = useMemo(() => { try { const value = JSON.parse(input) as Shape; return { output: inferInterfaces(value, root || "Root", mode), error: "" }; } catch (error) { return { output: "", error: jsonError(input, error) }; } }, [input, root, mode]);
  function format() { try { setInput(JSON.stringify(JSON.parse(input), null, 2)); } catch {} }
  return <div className="workbench-stack"><section className="json-toolbar"><label>Root type name<input value={root} onChange={(e) => setRoot(e.target.value)} /></label><div className="template-tabs">{["interface", "type"].map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{item}</button>)}</div><button className="secondary-button" onClick={format}>JSON 정렬</button></section><section className="workbench two-col code-columns"><div className="panel"><div className="panel-head"><span>01</span><div><h2>JSON 입력</h2><p>중첩 객체와 배열도 자동으로 읽어요.</p></div></div><textarea className={`code-input json-editor ${parsed.error ? "has-error" : ""}`} value={input} spellCheck={false} onChange={(e) => setInput(e.target.value)} />{parsed.error ? <p className="inline-error">{parsed.error}</p> : <p className="inline-success"><CheckCircle2 size={15} /> 올바른 JSON입니다.</p>}</div><div className="panel"><div className="panel-head"><span>02</span><div><h2>TypeScript 결과</h2><p>바로 복사해 프로젝트에 붙여 넣으세요.</p></div></div><OutputCard title={`${root || "Root"}.ts`} value={parsed.output} language="typescript" /></div></section></div>;
}

function sanitizeSvg(value: string) { if (!/^\s*<svg[\s>]/i.test(value) || !/<\/svg>\s*$/i.test(value)) throw new Error("올바른 SVG 코드를 입력해 주세요."); return value.replace(/<\?(?:xml)[^>]*>/gi, "").replace(/<!DOCTYPE[^>]*>/gi, "").replace(/<(script|foreignObject|iframe|object|embed)\b[^>]*>[\s\S]*?<\/\1>/gi, "").replace(/<(script|foreignObject|iframe|object|embed)\b[^>]*\/?\s*>/gi, "").replace(/\s+on[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "").replace(/\s+(?:href|xlink:href)\s*=\s*(["'])\s*(?:javascript:|data:text\/html)[\s\S]*?\1/gi, ""); }
function optimizeSvg(value: string) { return sanitizeSvg(value).replace(/<!--[^]*?-->/g, "").replace(/>\s+</g, "><").replace(/\s{2,}/g, " ").trim(); }
function svgToReact(value: string) { const safe = optimizeSvg(value).replace(/class=/g, "className=").replace(/stroke-width=/g, "strokeWidth=").replace(/stroke-linecap=/g, "strokeLinecap=").replace(/stroke-linejoin=/g, "strokeLinejoin=").replace(/fill-rule=/g, "fillRule=").replace(/clip-rule=/g, "clipRule=").replace(/tabindex=/g, "tabIndex="); return `import type { SVGProps } from "react";\n\nexport function Icon(props: SVGProps<SVGSVGElement>) {\n  return (\n    ${safe.replace("<svg", "<svg {...props}")}\n  );\n}`; }

export function SvgTool() {
  const sample = `<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg">\n  <rect x="12" y="12" width="96" height="96" rx="24" fill="#111827"/>\n  <path d="M38 61l14 14 31-34" fill="none" stroke="#ff5c35" stroke-width="10" stroke-linecap="round"/>\n</svg>`;
  const [input, setInput] = useState(sample); const [size, setSize] = useState(512); const result = useMemo(() => { try { const safe = sanitizeSvg(input); return { safe, optimized: optimizeSvg(input), react: svgToReact(input), error: "" }; } catch (error) { return { safe: "", optimized: "", react: "", error: error instanceof Error ? error.message : "SVG를 처리할 수 없습니다." }; } }, [input]);
  const preview = result.safe ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(result.safe)}` : "";
  async function png() { if (!preview) return; const image = await loadImage(preview); const canvas = document.createElement("canvas"); canvas.width = size; canvas.height = size; canvas.getContext("2d")!.drawImage(image, 0, 0, size, size); downloadBlob(await canvasToBlob(canvas), `svg-${size}x${size}.png`); }
  return <div className="workbench-stack"><section className="workbench two-col code-columns"><div className="panel"><div className="panel-head"><span>01</span><div><h2>SVG Code</h2><p>위험한 script와 event 속성은 제거됩니다.</p></div></div><textarea className={`code-input json-editor ${result.error ? "has-error" : ""}`} value={input} spellCheck={false} onChange={(e) => setInput(e.target.value)} />{result.error && <p className="inline-error">{result.error}</p>}<button className="secondary-button" onClick={() => setInput(result.optimized)} disabled={!result.optimized}>SVG 최적화 적용</button></div><div className="panel"><div className="panel-head"><span>02</span><div><h2>안전한 미리보기</h2><p>코드를 DOM에 직접 실행하지 않아요.</p></div></div><div className="svg-preview">{preview ? <img src={preview} alt="SVG 미리보기" /> : <span>미리볼 수 없는 SVG예요.</span>}</div><div className="download-row"><label>PNG 크기<select value={size} onChange={(e) => setSize(Number(e.target.value))}>{[64, 128, 256, 512, 1024].map((n) => <option key={n} value={n}>{n}×{n}</option>)}</select></label><button className="primary-button" onClick={png} disabled={!preview}><Download size={17} /> PNG 다운로드</button></div></div></section><OutputCard title="React Component" value={result.react} language="tsx" /></div>;
}

const promptOptions = ["기존 기능 유지", "기존 디자인 유지", "불필요한 리팩터링 금지", "기존 DB 재사용", "새로운 dependency 최소화", "TypeScript 오류 확인", "Build 실행", "변경파일 설명", "보안 문제 확인"];
export function PromptBuilderTool() {
  const [agent, setAgent] = useState("Codex"); const [framework, setFramework] = useState("Next.js"); const [goal, setGoal] = useState("회원가입 기능을 추가하고 싶어."); const [options, setOptions] = useState(promptOptions); const [extra, setExtra] = useState("");
  const prompt = useMemo(() => `현재 프로젝트 구조와 package.json을 먼저 분석한 뒤 작업해줘.\n\n## 목표\n${goal.trim() || "구현 목표를 입력해 주세요."}\n\n## 현재 프로젝트 확인\n- 기존 기술 스택과 라우팅 방식을 확인할 것\n- 이미 구현된 기능과 공통 컴포넌트를 우선 재사용할 것\n- 대상 환경: ${framework}\n- 사용할 AI 도구: ${agent}\n\n## 구현 요구사항\n- 요청한 기능이 실제 사용자 흐름에서 동작하도록 구현할 것${extra.trim() ? `\n- 추가 조건: ${extra.trim()}` : ""}\n\n## 제약사항\n${options.filter((x) => x.includes("유지") || x.includes("금지") || x.includes("재사용") || x.includes("최소화")).map((x) => `- ${x}`).join("\n") || "- 현재 프로젝트 구조를 존중할 것"}\n\n## 검증\n${options.filter((x) => x.includes("오류") || x.includes("Build") || x.includes("보안")).map((x) => `- ${x}`).join("\n") || "- 주요 사용자 흐름 확인"}\n\n## 완료 후\n${options.includes("변경파일 설명") ? "- 변경 파일과 구현 내용을 요약할 것\n" : ""}- 실행 결과와 남은 주의사항을 알려줄 것`, [agent, framework, goal, options, extra]);
  return <div className="workbench-stack"><section className="workbench prompt-layout"><div className="panel"><div className="panel-head"><span>01</span><div><h2>작업 조건</h2><p>AI가 놓치면 안 되는 내용을 체크하세요.</p></div></div><div className="form-stack"><label>사용 AI<select value={agent} onChange={(e) => setAgent(e.target.value)}>{["Codex", "Cursor", "Claude Code", "Lovable", "Bolt", "v0", "기타"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Framework<select value={framework} onChange={(e) => setFramework(e.target.value)}>{["Next.js", "React", "Vite", "Vue", "Nuxt", "Supabase", "기타"].map((x) => <option key={x}>{x}</option>)}</select></label><label>무엇을 만들고 싶나요?<textarea rows={4} value={goal} onChange={(e) => setGoal(e.target.value)} /></label><fieldset><legend>기본 안전장치</legend><div className="option-checks">{promptOptions.map((item) => <label key={item}><input type="checkbox" checked={options.includes(item)} onChange={() => setOptions((now) => now.includes(item) ? now.filter((x) => x !== item) : [...now, item])} /><span>{item}</span></label>)}</div></fieldset><label>추가 조건<textarea rows={3} value={extra} placeholder="예: 모바일에서 먼저 확인해줘." onChange={(e) => setExtra(e.target.value)} /></label></div></div><div className="panel prompt-result"><div className="panel-head"><span>02</span><div><h2>완성된 프롬프트</h2><p>복사해서 AI 코딩 도구에 바로 붙여 넣으세요.</p></div></div><div className="prompt-icon"><WandSparkles size={20} /></div><OutputCard title={`${agent} Prompt`} value={prompt} language="markdown" /></div></section></div>;
}

function escapeQuote(value: string) { return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " "); }
function htmlEscape(value: string) { return value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
